// <auto-generated />
namespace TokenMaster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StandsandDevicesupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StandsandDevicesupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201706070917577_Stands and Devices updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
